"""Repository del dominio (RNF-01): intenti, proposte, ordini, rifiuti e catalogo stanno fuori dal processo."""
from datetime import datetime
from typing import Iterable, List, Optional, Protocol, Set

from vela.domain.models import Intent, Order, OrderStatus, Product, Proposal, Rejection


class DuplicateOrder(Exception):
    """Esiste già un ordine per la proposta (RNF-03)."""


class ProductRepository(Protocol):
    def upsert_many(self, products: Iterable[Product]) -> None: ...
    def count(self) -> int: ...
    def list_all(self) -> List[Product]: ...
    def get(self, product_id: str) -> Optional[Product]: ...
    def last_fetched_at(self) -> Optional[datetime]: ...


class IntentRepository(Protocol):
    def add(self, intent: Intent) -> None: ...
    def get(self, intent_id: str) -> Optional[Intent]: ...


class ProposalRepository(Protocol):
    def add(self, proposal: Proposal) -> None: ...
    def get(self, proposal_id: str) -> Optional[Proposal]: ...
    def list_for_intent(self, intent_id: str) -> List[Proposal]: ...


class OrderRepository(Protocol):
    def add(self, order: Order) -> None: ...
    def get(self, order_id: str) -> Optional[Order]: ...
    def get_by_proposal(self, proposal_id: str) -> Optional[Order]: ...
    def save(self, order: Order) -> None: ...
    def ids_with_status(self, status: OrderStatus) -> List[str]: ...


class RejectionRepository(Protocol):
    def add(self, rejection: Rejection) -> None: ...
    def product_ids_for_intent(self, intent_id: str) -> Set[str]: ...
    def proposal_ids_for_intent(self, intent_id: str) -> Set[str]: ...


class WebhookEventRepository(Protocol):
    """Eventi Stripe già presi in carico (RNF-03): il primo claim vince, release lo annulla."""
    def claim(self, event_id: str, event_type: str, at: datetime) -> bool: ...
    def release(self, event_id: str) -> None: ...


class Repositories(Protocol):
    products: ProductRepository
    intents: IntentRepository
    proposals: ProposalRepository
    orders: OrderRepository
    rejections: RejectionRepository
    webhook_events: WebhookEventRepository
