"""Repository del dominio (RNF-01): intenti, proposte, ordini, rifiuti e catalogo stanno fuori dal processo."""
from datetime import datetime
from typing import Dict, Iterable, List, NamedTuple, Optional, Protocol, Set

from vela.domain.models import (Criteria, Intent, Order, OrderStatus, Product, Proposal,
                                Rejection)
from vela.ports.jobs import JobRepository
from vela.ports.quota import QuotaStore


class DuplicateOrder(Exception):
    """Esiste già un ordine per la proposta (RNF-03)."""


class SyncState(NamedTuple):
    """Quanto serve al sync (M10) per decidere se scaricare il dettaglio di un prodotto."""
    brand: Optional[str]
    updated_at: Optional[str]
    archived: bool


class ProductRepository(Protocol):
    def upsert_many(self, products: Iterable[Product]) -> None: ...
    def count(self) -> int: ...
    def list_all(self) -> List[Product]: ...
    def get(self, product_id: str) -> Optional[Product]: ...
    def last_fetched_at(self) -> Optional[datetime]: ...
    def set_bookable(self, product_id: str, bookable: bool, checked_at: datetime) -> None: ...
    def archive_missing(self, keep_ids: Iterable[str], brand: Optional[str] = None) -> int: ...
    def sync_state(self, ids: Iterable[str]) -> Dict[str, SyncState]: ...
    def mark_seen(self, ids: Iterable[str], brand: str, sport: str, seen_at: datetime) -> None: ...


class IntentRepository(Protocol):
    def add(self, intent: Intent) -> None: ...
    def get(self, intent_id: str) -> Optional[Intent]: ...
    def update_criteria(self, intent_id: str, criteria: Criteria) -> None: ...


class ProposalRepository(Protocol):
    def add(self, proposal: Proposal) -> None: ...
    def get(self, proposal_id: str) -> Optional[Proposal]: ...
    def list_for_intent(self, intent_id: str) -> List[Proposal]: ...


class OrderRepository(Protocol):
    def add(self, order: Order) -> None: ...
    def get(self, order_id: str) -> Optional[Order]: ...
    def get_by_proposal(self, proposal_id: str) -> Optional[Order]: ...
    def get_by_replacement(self, proposal_id: str) -> Optional[Order]: ...
    def save(self, order: Order) -> None: ...
    def ids_with_status(self, status: OrderStatus) -> List[str]: ...


class RejectionRepository(Protocol):
    def add(self, rejection: Rejection) -> None: ...
    def product_ids_for_intent(self, intent_id: str) -> Set[str]: ...
    def proposal_ids_for_intent(self, intent_id: str) -> Set[str]: ...
    def list_for_intent(self, intent_id: str) -> List[Rejection]: ...


class Repositories(Protocol):
    products: ProductRepository
    intents: IntentRepository
    proposals: ProposalRepository
    orders: OrderRepository
    rejections: RejectionRepository
    jobs: JobRepository
    quota: QuotaStore
