import json
import os
import subprocess
import sys
import tempfile
import unittest
from datetime import datetime, timezone

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "scripts"))
import agents_log  # noqa: E402

SESSION = "1adaf043-50f4-43fa-825d-2c09407d0f42"


def line(obj):
    return json.dumps(obj)


def user(content, ts, **extra):
    d = {"type": "user", "isSidechain": False, "timestamp": ts,
         "message": {"role": "user", "content": content}, "sessionId": SESSION}
    d.update(extra)
    return line(d)


def assistant(blocks, ts, **extra):
    d = {"type": "assistant", "isSidechain": False, "timestamp": ts,
         "message": {"role": "assistant", "content": blocks}, "sessionId": SESSION}
    d.update(extra)
    return line(d)


T0 = "2026-09-24T21:10:48.356Z"
T1 = "2026-09-24T21:10:54.627Z"
T2 = "2026-09-24T21:11:07.000Z"

FIXTURE = [
    line({"type": "permission-mode", "permissionMode": "plan", "sessionId": SESSION}),
    user("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>", T0),
    user("<command-name>/clear</command-name>", T0),
    user("Obiettivo: trascrivere le chat con gli agenti\n\n<system-reminder>\nhidden\n</system-reminder>", T0),
    line({"type": "ai-title", "aiTitle": "Trascrizione chat agenti", "sessionId": SESSION}),
    assistant([{"type": "thinking", "thinking": "secret thoughts"},
               {"type": "text", "text": "Comincio."},
               {"type": "tool_use", "id": "t1", "name": "Bash",
                "input": {"command": "ls -la", "description": "List files"}}], T1),
    user([{"type": "tool_result", "tool_use_id": "t1", "content": "file list output"}], T1),
    user([{"type": "text", "text": "Base directory for this skill: /x"}], T1, isMeta=True),
    assistant([{"type": "tool_use", "id": "t2", "name": "Edit",
                "input": {"file_path": "/repo/src/app.py", "old_string": "a", "new_string": "b"}}], T2),
    assistant([{"type": "text", "text": "subagent chatter"}], T2, isSidechain=True),
    user([{"type": "text", "text": "Grazie, procedi."}], T2),
    assistant([{"type": "text", "text": "Fatto."}], T2),
]


class IsGitCommitTest(unittest.TestCase):
    def test_plain_commit(self):
        self.assertTrue(agents_log.is_git_commit("git commit -m 'x'"))

    def test_status_is_not_commit(self):
        self.assertFalse(agents_log.is_git_commit("git status"))

    def test_chained_commit(self):
        self.assertTrue(agents_log.is_git_commit("git add . && git commit -m x"))

    def test_word_commit_without_git(self):
        self.assertFalse(agents_log.is_git_commit("echo commit"))


class ParseTranscriptTest(unittest.TestCase):
    def setUp(self):
        self.entries, self.meta = agents_log.parse_transcript(FIXTURE)

    def test_keeps_user_and_assistant_text(self):
        kinds = [(e.role, e.text) for e in self.entries if e.role != "tool"]
        self.assertEqual(kinds, [
            ("user", "Obiettivo: trascrivere le chat con gli agenti"),
            ("assistant", "Comincio."),
            ("user", "Grazie, procedi."),
            ("assistant", "Fatto."),
        ])

    def test_one_tool_entry_per_tool_use(self):
        tools = [e.text for e in self.entries if e.role == "tool"]
        self.assertEqual(tools, ["Bash: List files", "Edit /repo/src/app.py"])

    def test_discards_noise(self):
        blob = "\n".join(e.text for e in self.entries)
        for noise in ("local-command-caveat", "/clear", "secret thoughts", "file list output",
                      "Base directory", "subagent chatter", "hidden", "system-reminder"):
            self.assertNotIn(noise, blob)

    def test_meta(self):
        self.assertEqual(self.meta["title"], "Trascrizione chat agenti")
        self.assertEqual(self.meta["session_id"], SESSION)

    def test_timestamps_are_aware_datetimes(self):
        self.assertEqual(self.entries[0].ts, datetime(2026, 9, 24, 21, 10, 48, 356000, tzinfo=timezone.utc))


class ToolLabelTest(unittest.TestCase):
    def test_bash_prefers_description(self):
        self.assertEqual(agents_log.tool_label("Bash", {"command": "rm x", "description": "Remove x"}), "Bash: Remove x")

    def test_bash_without_description_truncates_command(self):
        label = agents_log.tool_label("Bash", {"command": "x" * 200})
        self.assertTrue(label.startswith("Bash: " + "x" * 80))
        self.assertTrue(label.endswith("…"))
        self.assertLessEqual(len(label), 6 + 81)

    def test_file_tools_use_path(self):
        self.assertEqual(agents_log.tool_label("Read", {"file_path": "/a/b.py"}), "Read /a/b.py")

    def test_skill_and_agent(self):
        self.assertEqual(agents_log.tool_label("Skill", {"skill": "foo:bar"}), "Skill foo:bar")
        self.assertEqual(agents_log.tool_label("Agent", {"description": "Search repo", "prompt": "..."}), "Agent: Search repo")

    def test_unknown_tool_is_name_only(self):
        self.assertEqual(agents_log.tool_label("Whatever", {"x": 1}), "Whatever")


class SessionFilenameTest(unittest.TestCase):
    def test_uses_local_time_and_slug(self):
        entries, _ = agents_log.parse_transcript(FIXTURE)
        name = agents_log.session_filename(entries)
        first = entries[0].ts.astimezone()
        self.assertEqual(name, first.strftime("%Y-%m-%d-%H%M") + "-obiettivo-trascrivere-le-chat-con-gli-ag.md")

    def test_slug_is_ascii_and_bounded(self):
        self.assertEqual(agents_log.slugify("Perché è così?! Àccènti & simboli"), "perche-e-cosi-accenti-simboli")
        self.assertEqual(len(agents_log.slugify("a " * 100)), 40 - 1)  # trailing dash trimmed

    def test_empty_slug_falls_back_to_session(self):
        entries, _ = agents_log.parse_transcript(FIXTURE)
        self.assertEqual(agents_log.session_filename([], session_id="abc12345-x"), None)


class RenderMarkdownTest(unittest.TestCase):
    def test_snapshot(self):
        entries, meta = agents_log.parse_transcript(FIXTURE)
        md = agents_log.render_markdown(entries, meta)
        h = lambda ts: agents_log.parse_ts(ts).astimezone().strftime("%H:%M")  # noqa: E731
        expected = "\n".join([
            "# Trascrizione chat agenti",
            "",
            "- Sessione: `%s`" % SESSION,
            "- Inizio: %s" % agents_log.parse_ts(T0).astimezone().strftime("%Y-%m-%d %H:%M"),
            "",
            "## Utente %s" % h(T0),
            "",
            "Obiettivo: trascrivere le chat con gli agenti",
            "",
            "## Agente %s" % h(T1),
            "",
            "Comincio.",
            "",
            "- 🔧 Bash: List files",
            "",
            "- 🔧 Edit /repo/src/app.py",
            "",
            "## Utente %s" % h(T2),
            "",
            "Grazie, procedi.",
            "",
            "## Agente %s" % h(T2),
            "",
            "Fatto.",
            "",
        ])
        self.assertEqual(md, expected)


class TranscribeTest(unittest.TestCase):
    def test_writes_markdown_and_identical_jsonl_copy(self):
        with tempfile.TemporaryDirectory() as tmp:
            transcript = os.path.join(tmp, "t.jsonl")
            raw = ("\n".join(FIXTURE) + "\n").encode("utf-8")
            with open(transcript, "wb") as f:
                f.write(raw)
            out_dir = os.path.join(tmp, "agents-log")
            md_path, jsonl_path = agents_log.transcribe(transcript, out_dir)
            self.assertTrue(md_path.endswith(".md"))
            self.assertEqual(jsonl_path, md_path[:-3] + ".jsonl")
            with open(jsonl_path, "rb") as f:
                self.assertEqual(f.read(), raw)

    def test_no_user_message_writes_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            transcript = os.path.join(tmp, "t.jsonl")
            with open(transcript, "w") as f:
                f.write(FIXTURE[0] + "\n")
            self.assertIsNone(agents_log.transcribe(transcript, os.path.join(tmp, "agents-log")))
            self.assertFalse(os.path.exists(os.path.join(tmp, "agents-log")))


class HookEndToEndTest(unittest.TestCase):
    def run_hook(self, cwd, command, transcript):
        payload = {"session_id": SESSION, "transcript_path": transcript, "cwd": cwd,
                   "hook_event_name": "PreToolUse", "tool_name": "Bash",
                   "tool_input": {"command": command}}
        script = os.path.join(os.path.dirname(__file__), "..", "scripts", "agents_log.py")
        return subprocess.run([sys.executable, script, "--hook"], input=json.dumps(payload),
                              cwd=cwd, capture_output=True, text=True)

    def test_commit_writes_and_stages_log(self):
        with tempfile.TemporaryDirectory() as tmp:
            subprocess.run(["git", "init", "-q"], cwd=tmp, check=True)
            transcript = os.path.join(tmp, "t.jsonl")
            with open(transcript, "w") as f:
                f.write("\n".join(FIXTURE) + "\n")
            res = self.run_hook(tmp, "git commit -m 'x'", transcript)
            self.assertEqual(res.returncode, 0, res.stderr)
            files = sorted(os.listdir(os.path.join(tmp, "agents-log")))
            self.assertEqual(len(files), 2)
            self.assertTrue(files[0].endswith("-obiettivo-trascrivere-le-chat-con-gli-ag.jsonl"))
            self.assertTrue(files[1].endswith("-obiettivo-trascrivere-le-chat-con-gli-ag.md"))
            staged = subprocess.run(["git", "diff", "--cached", "--name-only"], cwd=tmp,
                                    capture_output=True, text=True).stdout.split()
            self.assertEqual(staged, ["agents-log/" + f for f in files])

    def test_non_commit_does_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            subprocess.run(["git", "init", "-q"], cwd=tmp, check=True)
            transcript = os.path.join(tmp, "t.jsonl")
            with open(transcript, "w") as f:
                f.write("\n".join(FIXTURE) + "\n")
            res = self.run_hook(tmp, "git status", transcript)
            self.assertEqual(res.returncode, 0)
            self.assertFalse(os.path.exists(os.path.join(tmp, "agents-log")))

    def test_missing_transcript_never_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            res = self.run_hook(tmp, "git commit -m x", os.path.join(tmp, "nope.jsonl"))
            self.assertEqual(res.returncode, 0)
            self.assertIn("agents_log", res.stderr)


if __name__ == "__main__":
    unittest.main()
